// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: syncdata.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SyncData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,8,opt,name=Code,proto3" json:"Code,omitempty"`
	Data []byte `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SyncData) Reset() {
	*x = SyncData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syncdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncData) ProtoMessage() {}

func (x *SyncData) ProtoReflect() protoreflect.Message {
	mi := &file_syncdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncData.ProtoReflect.Descriptor instead.
func (*SyncData) Descriptor() ([]byte, []int) {
	return file_syncdata_proto_rawDescGZIP(), []int{0}
}

func (x *SyncData) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncOffset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *SyncOffset) Reset() {
	*x = SyncOffset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syncdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOffset) ProtoMessage() {}

func (x *SyncOffset) ProtoReflect() protoreflect.Message {
	mi := &file_syncdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOffset.ProtoReflect.Descriptor instead.
func (*SyncOffset) Descriptor() ([]byte, []int) {
	return file_syncdata_proto_rawDescGZIP(), []int{1}
}

func (x *SyncOffset) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_syncdata_proto protoreflect.FileDescriptor

var file_syncdata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x32, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63,
	0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_syncdata_proto_rawDescOnce sync.Once
	file_syncdata_proto_rawDescData = file_syncdata_proto_rawDesc
)

func file_syncdata_proto_rawDescGZIP() []byte {
	file_syncdata_proto_rawDescOnce.Do(func() {
		file_syncdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_syncdata_proto_rawDescData)
	})
	return file_syncdata_proto_rawDescData
}

var file_syncdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_syncdata_proto_goTypes = []interface{}{
	(*SyncData)(nil),   // 0: pb.SyncData
	(*SyncOffset)(nil), // 1: pb.SyncOffset
}
var file_syncdata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_syncdata_proto_init() }
func file_syncdata_proto_init() {
	if File_syncdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_syncdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syncdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncOffset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_syncdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_syncdata_proto_goTypes,
		DependencyIndexes: file_syncdata_proto_depIdxs,
		MessageInfos:      file_syncdata_proto_msgTypes,
	}.Build()
	File_syncdata_proto = out.File
	file_syncdata_proto_rawDesc = nil
	file_syncdata_proto_goTypes = nil
	file_syncdata_proto_depIdxs = nil
}
